services:
  caddy-www:
    networks:
      - proxy
    image: pknw1/www.pknw1.co.uk:latest
    container_name: caddy-www
    hostname: caddy-www
    environment:
      - VIRTUAL_HOST=pknw1.co.uk,www.pknw1.co.uk
      - VIRTUAL_PORT=80


networks:
  proxy:
    external: true
    name: proxy

